### ISSUE TITLE
论文中Figure 3中的数值问题

### ISSUE THREAD

**Issue by 0x00-pl** [FMInference/H2O#3]
![图片](https://github.com/FMInference/H2O/assets/2049889/ade2b03d-dd22-47e3-a3a5-3c62cda8afaf)
框出来的这两组数据是不是应该是一致的?

**Comment by chenhongyu2048** [comment]
你看明白这篇文章了吗😂我感觉他写得不清不楚的，特别是那个算法1的部分（Si好像在定义前就被使用了）
而且图3这里的计算也没写清楚

**Comment by Kyriection** [comment]
Thanks for pointing this out. We've updated the number in Figure 3 and also the algorithm. Please check the camera-ready version. Thanks!

**Comment by slatter666** [comment]
There‘s another problem of this image, since at decoding step5 the first token's score is 0.03 larger than the second's score 0.02. For global statistic, the first token's score should be definately larger than the second token's score, however 0.03 < 0.04
