### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by li2haipeng** [FMInference/H2O#5]
Hi,
I tried h20_hf/run_text_generation.py with and without HH enabled separately on 1xA100 GPU (40G). And my observation is HF can be even faster (30 tokens/s vs 25 tokens/s) and consume less GPU memory (13GB vs 26GB) than when HH is enabled, which is different from what it's claimed in the paper. Not sure if I run the code in a wrong way or what.

Thanks!

**Comment by yhyu13** [comment]
> [h2o_hf](https://github.com/FMInference/H2O/blob/main/h2o_hf): Testing the performance on different benchmarks, the code is based on [Hugging Face](https://github.com/huggingface/transformers). And we plan to work on the real throughput improvement based on Hugging Face framework.

In readme, I don't think the code is actually optimized in interms of HF framework? Therefore, there is no improvement, I believe
