### ISSUE TITLE
H20单任务推理问题（推理时间和显存占有率似乎没有优化效果）

### ISSUE THREAD

**Issue by SUSTechBruce** [FMInference/H2O#6]
测试一下单prompt推理时间，同样的5000tokens长度生成下，为啥H20的生成时间比full cache长，同时推理GPU显存占用多于full cache呢？
？

(new) [brucewan666@a0015 h2o_hf]$ python -u run_text_generation.py --model_arch llama --model_name huggyllama/llama-7b --recent_ratio 0.1 --heavy_ratio 0.1 
################# args.n_gpu ############:  4
10/31/2023 02:07:12 - WARNING - __main__ - device: cuda, n_gpu: 4, 16-bits training: False
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s]
################## Generated Context with Heavy Hitter Oracle ###################
Time cost to generate long context with token pruning:  216.37573313713074
(new) [brucewan666@a0015 h2o_hf]$ python -u run_text_generation.py --model_arch llama --model_name huggyllama/llama-7b --recent_ratio 0.1 --heavy_ratio 0.1 
################# args.n_gpu ############:  4
10/31/2023 02:12:09 - WARNING - __main__ - device: cuda, n_gpu: 4, 16-bits training: False
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
################## Generated Context with Full Cache ###################
Time cost to generate long context Full Cache:  148.36471390724182

**Comment by Kyriection** [comment]
Hi, Thanks for raising this issue. 

The previous HF code is the simulation version of KV Cache eviction policy, which applys a masking operation to the evicted KVs. Thus there are no memory saving or inference speed improvements. You can find the hf_flexgen code for speed testing. Now we uploaded the real dropping implementation with HF code-base. Please check this command:

# Full KV Cache
bash scripts/streaming/eval.sh full

# H2O
bash scripts/streaming/eval.sh h2o

**Comment by Kyriection** [comment]
> > Hi, Thanks for raising this issue.
> > The previous HF code is the simulation version of KV Cache eviction policy, which applys a masking operation to the evicted KVs. Thus there are no memory saving or inference speed improvements. You can find the hf_flexgen code for speed testing. Now we uploaded the real dropping implementation with HF code-base. Please check this command:
> > # Full KV Cache
> > bash scripts/streaming/eval.sh full
> > # H2O
> > bash scripts/streaming/eval.sh h2o
> 
> Hi. @Kyriection H2O is not compatible with flash attention right?

Hi. Our current implementation doesn't use flash attention. Since flash attention fuses all the computation in the CUDA kernel and will not return the attention scores. We are working on to incorporate H2O with flash attention by modifying the CUDA kernel or via the Triton code. We will release this implementation shortly.

**Comment by carriex** [comment]
Hi there! Thanks for the great work, I am wondering if there is any update on making flash attention compatible with H2O?
