### ISSUE TITLE
ModuleNotFoundError: No module named 'streaming_llm'

### ISSUE THREAD

**Issue by haiasd** [FMInference/H2O#8]
error while run `bash scripts/streaming/eval.sh full`
![image](https://github.com/FMInference/H2O/assets/26181650/e18118c6-ca59-42dd-a21c-1ebd2469d0ba)

**Comment by haiasd** [comment]
![image](https://github.com/FMInference/H2O/assets/26181650/7fd992bc-8a09-48cd-8cf2-e168a1db9ec7)
I install this repo：https://github.com/mit-han-lab/streaming-llm/tree/main/streaming_llm
but there is another error.

**Comment by ChuanhongLi** [comment]
> ![image](https://private-user-images.githubusercontent.com/26181650/289458894-7fd992bc-8a09-48cd-8cf2-e168a1db9ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODE5NTYsIm5iZiI6MTcwMjI4MTY1NiwicGF0aCI6Ii8yNjE4MTY1MC8yODk0NTg4OTQtN2ZkOTkyYmMtOGEwOS00OGNkLThjZjItZTE2OGExZGI5ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTI4NjdkYzY5MjViNDFjMDcwNzY4ZjhjZTkyNGRmYjdjZmFjMzU0Y2RiZGU5Mjc3ZmFmZjkxZGEwYWVlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KqyYP5KTbH5lwHFjYwMkZCQSs0HxCDUy4OfxDmfEQTk) I install this repo：https://github.com/mit-han-lab/streaming-llm/tree/main/streaming_llm but there is another error.

Maybe you should use "from utils_real_drop.stream import load, download_url, load_jsonl". And in streamingllm, the load function just only has one parameter,  so you can use load(model_name_or_path).

**Comment by yyfcc17** [comment]
this bug is still not fixed, and i found another in h2o_hf/run_streaming.py, seem that your code is not well tested
