### ISSUE TITLE
ModuleNotFoundError: No module named 'lost_in_the_middle'

### ISSUE THREAD

**Issue by haiasd** [FMInference/H2O#9]
error while run `bash scripts/summarization/eval.sh xsum 0 full 0`
![image](https://github.com/FMInference/H2O/assets/26181650/cbced11c-c00d-42ac-95a0-20cbbb02276f)

**Comment by ChuanhongLi** [comment]
> error while run `bash scripts/summarization/eval.sh xsum 0 full 0` ![image](https://private-user-images.githubusercontent.com/26181650/289461808-cbced11c-c00d-42ac-95a0-20cbbb02276f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA0MjksIm5iZiI6MTcwMjQ2MDEyOSwicGF0aCI6Ii8yNjE4MTY1MC8yODk0NjE4MDgtY2JjZWQxMWMtYzAwZC00MmFjLTk1YTAtMjBjYmJiMDIyNzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYmE4YTc5NzZjZDI3YTIzMDBhN2JhMTdmZjQ3MmViYTFhYmIwYjNlODRlZWY1YTk4M2Y1YmI3YjgwOWEwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixXDrfDPVUjYMly8zEi1eDFQ4qYP-0CzaWUhyhGITwg)

![image](https://github.com/FMInference/H2O/assets/90491543/ab99b16b-e0b6-4606-881b-6314bf198cdc)
In fact, these codes are not used in the file "run_summarization.py", so just let them go...
